export const projectConstants = {
  GETALL_REQUEST: 'PROJECTS_GETALL_REQUEST',
  GETALL_SUCCESS: 'PROJECTS_GETALL_SUCCESS',
  GETALL_FAILURE: 'PROJECTS_GETALL_FAILURE',

  CREATE_REQUEST: 'PROJECTS_CREATE_REQUEST',
  CREATE_SUCCESS: 'PROJECTS_CREATE_SUCCESS',
  CREATE_FAILURE: 'PROJECTS_CREATE_FAILURE',

  START_EDITING:  'PROJECT_START_EDITING',
  CANCEL_EDITING: 'PROJECT_CANCEL_EDITING',

  UPDATE_REQUEST: 'PROJECTS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PROJECTS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PROJECTS_UPDATE_FAILURE',

  DELETE_REQUEST: 'PROJECTS_DELETE_REQUEST',
  DELETE_SUCCESS: 'PROJECTS_DELETE_SUCCESS',
  DELETE_FAILURE: 'PROJECTS_DELETE_FAILURE',
};

// //Create
// export const CREATE_TODO = '[Todo] CREATE_TODO' 
// export const CREATE_TODO_SUCCESS = '[Todo] CREATE_TODO_SUCCESS' 
// export const CREATE_TODO_ERROR = '[Todo] CREATE_TODO_ERROR' 


// //Read
// export const GET_TODOS = '[Todo] GET_TODOS' 
// export const GET_TODOS_SUCCESS = '[Todo] GET_TODOS_SUCCESS' 
// export const GET_TODOS_ERROR = '[Todo] GET_TODOS_ERROR' 


// //Update
// export const START_EDITING ='[Todo] START_EDITING'
// export const CANCEL_EDITING = '[Todo] CANCEL_EDITING'

// export const UPDATE_TODO = '[Todo] UPDATE_TODO' 
// export const UPDATE_TODO_SUCCESS = '[Todo] UPDATE_TODO_SUCCESS' 
// export const UPDATE_TODO_ERROR = '[Todo] UPDATE_TODO_ERROR' 

// export const COMPLETE_TODO = 'COMPLETE_TODO'


// //Delete
// export const DELETE_TODO = '[Todo] DELETE_TODO'
// export const DELETE_TODO_SUCCESS = '[Todo] DELETE_TODO_SUCCESS'
// export const DELETE_TODO_ERROR = '[Todo] DELETE_TODO_ERROR'
