export const projectConstants = {
  GETALL_REQUEST: 'PROJECTS_GETALL_REQUEST',
  GETALL_SUCCESS: 'PROJECTS_GETALL_SUCCESS',
  GETALL_FAILURE: 'PROJECTS_GETALL_FAILURE',

  DELETE_REQUEST: 'PROJECTS_DELETE_REQUEST',
  DELETE_SUCCESS: 'PROJECTS_DELETE_SUCCESS',
  DELETE_FAILURE: 'PROJECTS_DELETE_FAILURE',
};
