export const projectConstants = {
  GETALL_REQUEST: 'PROJECTS_GETALL_REQUEST',
  GETALL_SUCCESS: 'PROJECTS_GETALL_SUCCESS',
  GETALL_FAILURE: 'PROJECTS_GETALL_FAILURE',

  CREATE_REQUEST: 'PROJECTS_CREATE_REQUEST',
  CREATE_SUCCESS: 'PROJECTS_CREATE_SUCCESS',
  CREATE_FAILURE: 'PROJECTS_CREATE_FAILURE',

  START_EDITING:  'PROJECT_START_EDITING',
  CANCEL_EDITING: 'PROJECT_CANCEL_EDITING',

  UPDATE_REQUEST: 'PROJECTS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PROJECTS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PROJECTS_UPDATE_FAILURE',

  DELETE_REQUEST: 'PROJECTS_DELETE_REQUEST',
  DELETE_SUCCESS: 'PROJECTS_DELETE_SUCCESS',
  DELETE_FAILURE: 'PROJECTS_DELETE_FAILURE',
};
